      MODULE LGRMODULE
         INTEGER, SAVE, POINTER ::ISCHILD,NGRDS,NPLBEG,NPRBEG,NPCBEG
         INTEGER, SAVE, POINTER ::NPLEND,NPREND,NPCEND,NCPP,NPL,IBOTFLG
         INTEGER, SAVE, POINTER ::ISHFLG,IBFLG,IUPBHSV,IUCBHSV
         INTEGER, SAVE, POINTER ::IUPBFSV,IUCBFSV,MXLGRITER,IOUTLGR 
         INTEGER, SAVE, POINTER ::NBNODES,NPBNODES
         INTEGER, SAVE, POINTER ::IBMAXH,IBMAXF,NCMAXH,NCMAXF
         INTEGER, SAVE, POINTER ::IFMPGRID                              !WSCHMID added IFMPGRID
         INTEGER, SAVE, POINTER ::ISFRGRID                              !WSCHMID added ISFRGRID
         REAL, SAVE, POINTER ::RELAXH,RELAXF,HCLOSELGR,FCLOSELGR
         REAL, SAVE, POINTER ::HDIFFM,FDIFFM
         REAL, SAVE, POINTER ::PRATIN,CRATIN,PRATOUT,CRATOUT 
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::IBPFLG
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::IEDG
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::JEDG
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::NCPPL
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::NODEH
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::NODEF
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::NCON
         INTEGER, SAVE, POINTER, DIMENSION(:,:)   ::KPLC
         INTEGER, SAVE, POINTER, DIMENSION(:,:)   ::IPLC
         INTEGER, SAVE, POINTER, DIMENSION(:,:)   ::JPLC
         INTEGER, SAVE, POINTER, DIMENSION(:,:)   ::IFACEGN
         INTEGER, SAVE, POINTER, DIMENSION(:)     ::NPINDX
         INTEGER, SAVE, POINTER, DIMENSION(:,:,:) ::ICBOUND
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::GNHEAD
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::DHGN
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::GNFLUX
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::GNFLUXR
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::GNFLUXOLD
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::HOLDC
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::CCC  !obsolete
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::CCR  !obsolete  
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::CCV  !obsolete  
         REAL, SAVE,    POINTER, DIMENSION(:,:)   ::GNCOND
         REAL, SAVE,    POINTER, DIMENSION(:)     ::VCB
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::HK
         REAL, SAVE,    POINTER, DIMENSION(:,:,:) ::VK
        TYPE LGRTYPE
         INTEGER, POINTER ::ISCHILD,NGRDS,NPLBEG,NPRBEG,NPCBEG
         INTEGER, POINTER ::NPLEND,NPREND,NPCEND,NCPP,NPL,IBOTFLG
         INTEGER, POINTER ::ISHFLG,IBFLG,IUPBHSV,IUCBHSV
         INTEGER, POINTER ::IUPBFSV,IUCBFSV,MXLGRITER,IOUTLGR
         INTEGER, POINTER ::NBNODES,NPBNODES
         INTEGER, POINTER ::IBMAXH,IBMAXF,NCMAXH,NCMAXF
         INTEGER, POINTER ::IFMPGRID                                    !WSCHMID added IFMPGRID
         INTEGER, POINTER ::ISFRGRID                                    !WSCHMID added ISFRGRID
         REAL, POINTER ::RELAXH,RELAXF,HCLOSELGR,FCLOSELGR,HDIFFM,FDIFFM
         REAL, POINTER ::PRATIN,CRATIN,PRATOUT,CRATOUT 
         INTEGER, POINTER,    DIMENSION(:)     ::IBPFLG
         INTEGER, POINTER,    DIMENSION(:)     ::IEDG
         INTEGER, POINTER,    DIMENSION(:)     ::JEDG
         INTEGER, POINTER,    DIMENSION(:)     ::NCPPL
         INTEGER, POINTER,    DIMENSION(:)     ::NODEH
         INTEGER, POINTER,    DIMENSION(:)     ::NODEF
         INTEGER, POINTER,    DIMENSION(:)     ::NCON
         INTEGER, POINTER,    DIMENSION(:,:)   ::KPLC
         INTEGER, POINTER,    DIMENSION(:,:)   ::IPLC
         INTEGER, POINTER,    DIMENSION(:,:)   ::JPLC
         INTEGER, POINTER,    DIMENSION(:,:)   ::IFACEGN
         INTEGER, POINTER,    DIMENSION(:)     ::NPINDX
         INTEGER, POINTER,    DIMENSION(:,:,:) ::ICBOUND
         REAL,    POINTER,    DIMENSION(:,:)   ::GNHEAD
         REAL,    POINTER,    DIMENSION(:,:)   ::DHGN
         REAL,    POINTER,    DIMENSION(:,:)   ::GNFLUX
         REAL,    POINTER,    DIMENSION(:,:)   ::GNFLUXR
         REAL,    POINTER,    DIMENSION(:,:)   ::GNFLUXOLD
         REAL,    POINTER,    DIMENSION(:,:,:) ::HOLDC
         REAL,    POINTER,    DIMENSION(:,:,:) ::CCC     !obsolete
         REAL,    POINTER,    DIMENSION(:,:,:) ::CCR     !obsolete 
         REAL,    POINTER,    DIMENSION(:,:,:) ::CCV     !obsolete  
         REAL,    POINTER,    DIMENSION(:,:)   ::GNCOND
         REAL,    POINTER,    DIMENSION(:)     ::VCB
         REAL,    POINTER,    DIMENSION(:,:,:) ::HK
         REAL,    POINTER,    DIMENSION(:,:,:) ::VK
        END TYPE
        TYPE(LGRTYPE), SAVE  ::LGRDAT(10)
      END MODULE LGRMODULE
